name: CI/CD for prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./website
          file: ./website/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sveltekit-prod:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the latest image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/sveltekit-prod:latest

            # Stop and remove the old container if it exists
            docker stop sveltekit-prod || true
            docker rm sveltekit-prod || true

            # Remove the old image to ensure the latest is used
            docker rmi ${{ secrets.DOCKER_USERNAME }}/sveltekit-prod:latest || true

            # Optional: Remove unused volumes
            docker volume prune -f

            # Run the new container
            docker run -d --name sveltekit-prod -p 4173:4173 ${{ secrets.DOCKER_USERNAME }}/sveltekit-prod:latest
